
package frontend;

import backend.MyPanel;
import backend.Shape;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ColorizeWindow extends javax.swing.JFrame implements Node{

    private Node parentNode;
    private MyPanel myPanel;
    
    private Color color;
    private Color fillColor;
    private Color defaultColor;
    private Color defaultFillColor;
    
    JComboBox<String> jComboBox1;
    
    public ColorizeWindow(MyPanel myPanel, JComboBox<String> jComboBox1, Color defaultColor, Color defaultFillColor) {
        initComponents();
        this.myPanel = myPanel;
        this.jComboBox1 = jComboBox1;
        this.defaultColor = defaultColor;
        this.defaultFillColor = defaultFillColor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectColorButton = new javax.swing.JButton();
        selectFillColorButton = new javax.swing.JButton();
        colorizeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        selectColorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectColorButton.setText("Select Color");
        selectColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectColorButtonActionPerformed(evt);
            }
        });

        selectFillColorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectFillColorButton.setText("Select Fill Color");
        selectFillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFillColorButtonActionPerformed(evt);
            }
        });

        colorizeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colorizeButton.setText("Colorize");
        colorizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(selectColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(selectColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectFillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        color = JColorChooser.showDialog(null, "Pick a color....", Color.black);
    }//GEN-LAST:event_selectColorButtonActionPerformed

    private void selectFillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFillColorButtonActionPerformed
        if(this.jComboBox1.getSelectedItem().toString().contains("LineSegment")){
            JOptionPane.showMessageDialog(null,"Line segments don't have a fill color.");
        }
        else{
            JColorChooser colorChooser = new JColorChooser();
            fillColor = JColorChooser.showDialog(null, "Pick a fill color....", Color.white);
        }
    }//GEN-LAST:event_selectFillColorButtonActionPerformed

    private void colorizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorizeButtonActionPerformed
        
        if(color == null){
            color = defaultColor;
        }
        if(fillColor == null){
            fillColor = defaultFillColor;
        }
        Shape[] shapes = myPanel.getShapes();
        for(int i=0; i<shapes.length; i++){
            if(this.jComboBox1.getSelectedItem().toString().equals(shapes[i].getName())){
                shapes[i].setColor(color);
                if(defaultFillColor != null){
                    shapes[i].setFillColor(fillColor);
                }
            }
        }
        closeWindow();
    }//GEN-LAST:event_colorizeButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeWindow();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorizeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorizeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorizeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorizeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorizeWindow(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorizeButton;
    private javax.swing.JButton selectColorButton;
    private javax.swing.JButton selectFillColorButton;
    // End of variables declaration//GEN-END:variables

    public void updateComboBox(){
        jComboBox1.removeAllItems();
        
        Shape[] shapes = myPanel.getShapes();
        for(int i=0; i<shapes.length; i++){
            jComboBox1.addItem(shapes[i].getName());
        }
    }
    
    public void closeWindow(){
        updateComboBox();
        
        this.setVisible(false);
        ((JFrame)this.getParentNode()).setVisible(true);   
    }
    
    @Override
    public void setParentNode(Node n) {
        this.parentNode = n;
    }

    @Override
    public Node getParentNode() {
        return parentNode;
    }
    
}
