
package frontend;

import backend.LineSegment;
import backend.MyPanel;
import backend.Shape;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class LineSegmentInfo extends javax.swing.JFrame implements Node {

    Node parentNode;
    MyPanel myPanel;
    
    Point p1;
    Point p2;
    Color color;
    private String name;
    
    JComboBox<String> jComboBox1;
    
    public LineSegmentInfo(MyPanel myPanel, JComboBox<String> jComboBox1) {
        initComponents();
        this.myPanel = myPanel;
        this.jComboBox1 = jComboBox1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstXCoordinateTextField = new javax.swing.JTextField();
        secondYCoordinateTextField = new javax.swing.JTextField();
        firstYCoordinateTextField = new javax.swing.JTextField();
        secondXCoordinateTextField = new javax.swing.JTextField();
        setColorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setText("Add Line");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("First X Coordinate");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Second X Coordinate");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Y Coordinate");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Second Y Coordinate");

        firstXCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstXCoordinateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstXCoordinateTextFieldActionPerformed(evt);
            }
        });

        secondYCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        firstYCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        secondXCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        setColorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        setColorButton.setText("Set Color");
        setColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(secondYCoordinateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstYCoordinateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(secondXCoordinateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstXCoordinateTextField))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstXCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstYCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secondXCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(secondYCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeWindow();  
    }//GEN-LAST:event_formWindowClosing

    private void setColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        color = JColorChooser.showDialog(null, "Pick a color....", Color.black);
    }//GEN-LAST:event_setColorButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try
        {
        if(firstXCoordinateTextField.getText().equals("")||firstYCoordinateTextField.getText().equals("")||secondXCoordinateTextField.getText().equals("")||secondYCoordinateTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Some fields are empty");
            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
        }
        else if(Integer.parseInt(firstXCoordinateTextField.getText())<0 || Integer.parseInt(firstYCoordinateTextField.getText())<0 || Integer.parseInt(secondXCoordinateTextField.getText())<0 || Integer.parseInt(secondYCoordinateTextField.getText())<0){
            JOptionPane.showMessageDialog(null,"Coordinates can't be negative");
            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
        }
        else{
            p1 = new Point(Integer.parseInt(firstXCoordinateTextField.getText()), Integer.parseInt(firstYCoordinateTextField.getText()));
            p2 = new Point(Integer.parseInt(secondXCoordinateTextField.getText()), Integer.parseInt(secondYCoordinateTextField.getText()));
            if(color == null){
                color = Color.black;
            }
            myPanel.increaseLineSegments();
            name = "LineSegment_"+myPanel.getNumberOfLineSegments();
            
            LineSegment line = new LineSegment(p1, p2);
            line.setColor(color);
            line.setName(name);
            myPanel.addShape(line);
            myPanel.refresh(null);
            
            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
            updateComboBox();
            closeWindow();
        }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You should enter numeric values in all fields");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void firstXCoordinateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstXCoordinateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstXCoordinateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LineSegmentInfo(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField firstXCoordinateTextField;
    private javax.swing.JTextField firstYCoordinateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField secondXCoordinateTextField;
    private javax.swing.JTextField secondYCoordinateTextField;
    private javax.swing.JButton setColorButton;
    // End of variables declaration//GEN-END:variables

    public void updateComboBox(){
        jComboBox1.removeAllItems();
        
        Shape[] shapes = myPanel.getShapes();
        for(int i=0; i<shapes.length; i++){
            jComboBox1.addItem(shapes[i].getName());
        }
    }
    
    public void closeWindow(){
        updateComboBox();
        
        this.setVisible(false);
        ((JFrame)this.getParentNode()).setVisible(true);   
    }
   
    @Override
    public void setParentNode(Node n) {
        this.parentNode = n;
    }

    @Override
    public Node getParentNode() {
        return parentNode;
    }
}
