
package frontend;

import backend.MyPanel;
import backend.Shape;
import backend.Triangle;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TriangleInfo extends javax.swing.JFrame implements Node{

    Node parentNode;
    MyPanel myPanel;
    private Point p1;
    private Point p2;
    private Point p3;
    private Color color;
    private Color fillColor;
    private String name;
    
    JComboBox<String> jComboBox1;
    
    public TriangleInfo(MyPanel myPanel, JComboBox<String> jComboBox1) {
        initComponents();
        
        this.myPanel = myPanel;
        this.jComboBox1 = jComboBox1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstYCoordinateTextField = new javax.swing.JTextField();
        secondXCoordinateTextField = new javax.swing.JTextField();
        setColorButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstXCoordinateTextField = new javax.swing.JTextField();
        secondYCoordinateTextField = new javax.swing.JTextField();
        thirdYCoordinateTextField = new javax.swing.JTextField();
        thirdXCoordinateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        setFillColorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        firstYCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        secondXCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        setColorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        setColorButton.setText("Set Color");
        setColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColorButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setText("Add Triangle");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("First X Coordinate");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Second X Coordinate");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Y Coordinate");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Second Y Coordinate");

        firstXCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstXCoordinateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstXCoordinateTextFieldActionPerformed(evt);
            }
        });

        secondYCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        thirdYCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        thirdXCoordinateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Third X Coordinate");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Third Y Coordinate");

        setFillColorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        setFillColorButton.setText("Set Fill Color");
        setFillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFillColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondXCoordinateTextField)
                            .addComponent(firstYCoordinateTextField)
                            .addComponent(firstXCoordinateTextField)
                            .addComponent(secondYCoordinateTextField)
                            .addComponent(thirdXCoordinateTextField)
                            .addComponent(thirdYCoordinateTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setFillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstXCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstYCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secondXCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(secondYCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdXCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdYCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(setFillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        color = JColorChooser.showDialog(null, "Pick a color....", Color.black);
    }//GEN-LAST:event_setColorButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try
        {
        if(firstXCoordinateTextField.getText().equals("")||firstYCoordinateTextField.getText().equals("")||secondXCoordinateTextField.getText().equals("")||secondYCoordinateTextField.getText().equals("")||thirdXCoordinateTextField.getText().equals("")||thirdYCoordinateTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Some fields are empty");
            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
            thirdXCoordinateTextField.setText("");
            thirdYCoordinateTextField.setText("");
        }
        else if(Integer.parseInt(firstXCoordinateTextField.getText())<0 || Integer.parseInt(firstYCoordinateTextField.getText())<0 || Integer.parseInt(secondXCoordinateTextField.getText())<0 || Integer.parseInt(secondYCoordinateTextField.getText())<0 || Integer.parseInt(thirdXCoordinateTextField.getText())<0 || Integer.parseInt(thirdYCoordinateTextField.getText())<0){
            JOptionPane.showMessageDialog(null,"Coordinates can't be negative");
            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
            thirdXCoordinateTextField.setText("");
            thirdYCoordinateTextField.setText("");
        }
        else{
            p1 = new Point(Integer.parseInt(firstXCoordinateTextField.getText()), Integer.parseInt(firstYCoordinateTextField.getText()));
            p2 = new Point(Integer.parseInt(secondXCoordinateTextField.getText()), Integer.parseInt(secondYCoordinateTextField.getText()));
            p3 = new Point(Integer.parseInt(thirdXCoordinateTextField.getText()), Integer.parseInt(thirdYCoordinateTextField.getText()));
            if(color == null){
                color = Color.black;
            }
            if(fillColor == null){
                fillColor = Color.white;
            }
            myPanel.increaseTriangles();
            name = "Triangle_"+myPanel.getNumberOfTriangles();

            Triangle triangle = new Triangle(p1, p2, p3);
            triangle.setColor(color);
            triangle.setFillColor(fillColor);
            triangle.setName(name);
            myPanel.addShape(triangle);
            myPanel.refresh(null);

            firstXCoordinateTextField.setText("");
            firstYCoordinateTextField.setText("");
            secondXCoordinateTextField.setText("");
            secondYCoordinateTextField.setText("");
            thirdXCoordinateTextField.setText("");
            thirdYCoordinateTextField.setText("");
            updateComboBox();
            closeWindow();
        }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You should enter numeric values in all fields");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void firstXCoordinateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstXCoordinateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstXCoordinateTextFieldActionPerformed

    private void setFillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFillColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        fillColor = JColorChooser.showDialog(null, "Pick a fill color....", Color.white);
    }//GEN-LAST:event_setFillColorButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeWindow();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangleInfo(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField firstXCoordinateTextField;
    private javax.swing.JTextField firstYCoordinateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField secondXCoordinateTextField;
    private javax.swing.JTextField secondYCoordinateTextField;
    private javax.swing.JButton setColorButton;
    private javax.swing.JButton setFillColorButton;
    private javax.swing.JTextField thirdXCoordinateTextField;
    private javax.swing.JTextField thirdYCoordinateTextField;
    // End of variables declaration//GEN-END:variables

    public void updateComboBox(){
        jComboBox1.removeAllItems();
        
        Shape[] shapes = myPanel.getShapes();
        for(int i=0; i<shapes.length; i++){
            jComboBox1.addItem(shapes[i].getName());
        }
    }
    
    public void closeWindow(){
        updateComboBox();
        
        this.setVisible(false);
        ((JFrame)this.getParentNode()).setVisible(true);   
    }
    
 
    
    @Override
    public void setParentNode(Node n) {
        this.parentNode = n;
    }

    @Override
    public Node getParentNode() {
        return parentNode;
    }
}
